-- MySQL Script generated by MySQL Workbench
-- Tue Oct 22 10:38:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema how-to-use-orm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `how-to-use-orm` ;

-- -----------------------------------------------------
-- Schema how-to-use-orm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `how-to-use-orm` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ;
SHOW WARNINGS;
USE `how-to-use-orm` ;

-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `category` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `modify_ts` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `modify_ts` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rel_category_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rel_category_product` (
  `category` BIGINT UNSIGNED NOT NULL,
  `product` BIGINT UNSIGNED NOT NULL,
  `modify_ts` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`category`, `product`),
  UNIQUE INDEX `REVERSE_PRIMARY` (`product` ASC, `category` ASC),
  CONSTRAINT `FK_CATEGORY_PRODUCT_PK_CATEGORY`
    FOREIGN KEY (`category`)
    REFERENCES `category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CATEGORY_PRODUCT_PK_PRODUCT`
    FOREIGN KEY (`product`)
    REFERENCES `product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `category`
-- -----------------------------------------------------
START TRANSACTION;
USE `how-to-use-orm`;
INSERT INTO `category` (`id`, `name`, `modify_ts`) VALUES (DEFAULT, 'test category #1', DEFAULT);
INSERT INTO `category` (`id`, `name`, `modify_ts`) VALUES (DEFAULT, 'test category #2', DEFAULT);
INSERT INTO `category` (`id`, `name`, `modify_ts`) VALUES (DEFAULT, 'test category #3', DEFAULT);
INSERT INTO `category` (`id`, `name`, `modify_ts`) VALUES (DEFAULT, 'test category #4', DEFAULT);
INSERT INTO `category` (`id`, `name`, `modify_ts`) VALUES (DEFAULT, 'test category #5', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `product`
-- -----------------------------------------------------
START TRANSACTION;
USE `how-to-use-orm`;
INSERT INTO `product` (`id`, `name`, `modify_ts`) VALUES (DEFAULT, 'test product #1', DEFAULT);
INSERT INTO `product` (`id`, `name`, `modify_ts`) VALUES (DEFAULT, 'test product #2', DEFAULT);
INSERT INTO `product` (`id`, `name`, `modify_ts`) VALUES (DEFAULT, 'test product #3', DEFAULT);
INSERT INTO `product` (`id`, `name`, `modify_ts`) VALUES (DEFAULT, 'test product #4', DEFAULT);
INSERT INTO `product` (`id`, `name`, `modify_ts`) VALUES (DEFAULT, 'test product #5', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `rel_category_product`
-- -----------------------------------------------------
START TRANSACTION;
USE `how-to-use-orm`;
INSERT INTO `rel_category_product` (`category`, `product`, `modify_ts`) VALUES (1, 1, DEFAULT);
INSERT INTO `rel_category_product` (`category`, `product`, `modify_ts`) VALUES (2, 2, DEFAULT);
INSERT INTO `rel_category_product` (`category`, `product`, `modify_ts`) VALUES (2, 3, DEFAULT);
INSERT INTO `rel_category_product` (`category`, `product`, `modify_ts`) VALUES (3, 4, DEFAULT);
INSERT INTO `rel_category_product` (`category`, `product`, `modify_ts`) VALUES (4, 4, DEFAULT);

COMMIT;

